language: java
notifications:
  slack:
    secure: WzdS5sSSQziwbZwqW8nCddRGC8SSrgcPyVn9NbV2MOkqa4mFawQOL05CCOc0RfV7otCCqxsDqXAehuyKzEVA8VrQ1g10Eelppbnv9WxDYzIj1M2MPmyo4RzHK6+aw0KRIujufgYQdxit+N/J2xATnUy+3hiXBQprCnIGXYaNk2w=
  hipchat:
    rooms:
      secure: A0rtcc5iWVOiKodiYxX8DzNn777k2boUWILXtfEKKXqHzxENYaj5EHeMT+kC+2F/rnnjS79fMFD9VU4d/dbjiQH4wzHMPA5gBGpOpb+q0zbLTxt4sYmn+9HqVoIu774ZSBkX1fh5y/MM6qrjUJbPLMuBylM88PhYu95hGL7TW1w=
deploy:
  provider: releases
  api_key:
    secure: Xn/EBDWawlEFeLjFmG0ZO0RlxzQ1Npzot4RF7ybwvJSwvskmhJbe4kqpuNeQgpjnVLOsNKvsWJrPtEEzLLUoKZI1oAVjzna8S6xHFmBP1wVmm4UREsl98YpXnywUQLVg1CU6ySfnq3wAfkPqh5eRFXAU8380FWEEwXO4/TNZhfUbvUVqly1NVwl8+TjBKHVaCBT4VlK7RlySA8UhLfFY0vXIszdRBXtYOKRJfOKhZ1rDN5sXxZxrHDTZgVpGTsNHaVZ+V4HRps3z8nU/s8EvBs9qQmkTUPh8W5dXmA9iIQwsXVtmI54vPML3M6bKL4RoD/B3ZfVmx0YXugBQWDZXDPR7oqiDeRCWeOVkqLAlvFpYZJhQbzOMGE+PihHTT0zarFAFYdI4OQGWTpKs4Sth5cjL6sXScOssdFxko7bk4hysX1gsN48/2WeDa6FPh94SLt4UB2muZleuZ2vJHHmTSS8xcBclfiM0M4WXzrZJiL96mpnejAASVYK/3MOMj0CLa0H2aFZcQl9wAsS1MWGbihOkxz7CfyenFkC8/Ie1CF83xBFCaDQHv/Fe7XSkMvbzSHqB6lQfLYb+LSkadJejhyoc5g6havaSMMtrgJ50bngZ9C/eFcT8P33ajRTi6/ah57+Fbf32efb3MOi6MVQhyHLJfEOhdFS9vs//V75DsLE=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-iib-plugin
